version: '3.6'
services:
    web:
      image: laravel
      build: ./laravel
      volumes:
        - ./www:/var/www/html
      env_file:
        - ./www/.env
      ports:
        - 80:80
      depends_on:
        - db
    db:
      image: mysql
      environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=homestead
        - MYSQL_USER=bob
        - MYSQL_PASSWORD=bob
